<%@ Page Language="C#" AutoEventWireup="true" CodeFile="QiYeHeSuanFangFa.aspx.cs"
    Inherits="Modules_GHG_SystemManage_QiYeHeSuanFangFa" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
            AutoGenerateSelectButton="True" EnableModelValidation="True" OnRowCancelingEdit="GridView1_RowCancelingEdit"
            OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating"
            AutoGenerateColumns="False">
            <Columns>
                <asp:BoundField ItemStyle-Width="80px" DataField="ID" HeaderText="公式编号" Visible="false" />
                <asp:BoundField ItemStyle-Width="100px" DataField="HangYeBianHao" HeaderText="所属行业" />
                <asp:BoundField ItemStyle-Width="500px" DataField="JiSuanGongShi" HeaderText="计算公式" />
            </Columns>
        </asp:GridView>
    </div>
    <p>
        <asp:Button ID="Button1" runat="server" Style="margin-left: 50px" Text="添加" Width="86px"
            OnClick="Button1_Click" />
    </p>
    </form>
</body>
</html>
