<%@ Page Language="C#" AutoEventWireup="true" CodeFile="QueShengZhiGuanLi.aspx.cs"
    Inherits="Modules_GHG_SystemManage_QueShengZhiGuanLi" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">


    <asp:Panel ID="Panel1" runat="server" Height="77px" Width="810px">
    <div style="margin-left:60px; margin-top:30px">
        <asp:Label ID="Label1" runat="server" Text="按行业查询："></asp:Label>
        <asp:DropDownList ID="DropDownList1" runat="server" Height="20px" 
            style="margin-left: 27px" Width="89px" 
            onselectedindexchanged="DropDownList1_SelectedIndexChanged" AutoPostBack="True" 
            >
        </asp:DropDownList>
        <asp:Button ID="Button1" runat="server" style="margin-left: 93px" 
            Text="查询" onclick="Button1_Click" />
        </div >
<%--
        <div style="margin-left:60px; margin-top:30px">
            <asp:Label ID="Label2" runat="server" Text="按燃料查询："></asp:Label>
            <asp:DropDownList ID="DropDownList2" runat="server" Height="16px" 
                style="margin-left: 28px" Width="77px">
            </asp:DropDownList>
        </div>--%>
    </asp:Panel>

    <div style="margin-top :10px; margin-left:auto">
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False"
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            AutoGenerateSelectButton="True" 
            onpageindexchanging="GridView1_PageIndexChanging" 
            onrowcancelingedit="GridView1_RowCancelingEdit" 
            onrowediting="GridView1_RowEditing" onrowdeleting="GridView1_RowDeleting" 
            PageSize="3" onrowupdating="GridView1_RowUpdating"  >
            <Columns>
            <asp:BoundField ItemStyle-Width="100px" DataField="ID" HeaderText="行业名称"  Visible="false"/>
                <asp:BoundField ItemStyle-Width="100px" DataField="HangYeBianHao" HeaderText="行业编号" ReadOnly="true"/>
                <asp:BoundField ItemStyle-Width="180px" DataField="RanLiaoID" HeaderText="燃料编号" ReadOnly="true" />
                <asp:BoundField ItemStyle-Width="100px" DataField="DiWeiFaReZhi" HeaderText="低位发热值" />
                <asp:BoundField ItemStyle-Width="100px" DataField="DanWeiReZhiHanTanLiang" HeaderText="单位热值含碳量" />
                <asp:BoundField ItemStyle-Width="100px" DataField="TanYangHuaLv" HeaderText="碳氧化率" />
                <asp:BoundField ItemStyle-Width="100px" DataField="DanWei" HeaderText="单位" />
            </Columns>
        </asp:GridView>
    </div>
    </form>
</body>
</html>
